### ISSUE TITLE
Crash on launch with Farmer's Delight  1.18.2

### ISSUE THREAD

**Issue by TheHarryXI** [Momo-Studios/Cold-Sweat-Rework-Forge#101]
The game crashed whilst rendering overlay
Error: java.lang.IllegalStateException: Failed to load description for particle farmersdelight:star

ColdSweat-2.1.11.1
FarmersDelight-1.18.2-1.2.0

**Comment by MisterAndyDandy** [comment]
I am having the same issue with another mod create_misc_and_things_1.18.2_1.1B.jar but I have got FarmersDelight-1.18.2-1.2.0 installed too

Edited I have tested it without ColdSweat-2.1.11.1 and it will work fine.

Edited I tested it without create_misc_and_things_1.18.2_1.1B.jar but still have ColdSweat-2.1.11.1 installed instead of getting error from create_misc_and_things instead I get the error about FarmersDelight-1.18.2-1.2.0 

create_misc_and_things => [crash-2022-10-31_15.10.04-client.txt](https://github.com/Momo-Studios/Cold-Sweat/files/9902380/crash-2022-10-31_15.10.04-client.txt)


FarmersDelight-1.18.2-1.2.0  => [crash-2022-10-31_15.17.59-client.txt](https://github.com/Momo-Studios/Cold-Sweat/files/9902452/crash-2022-10-31_15.17.59-client.txt)

**Comment by MisterAndyDandy** [comment]
I tested older versions of ColdSweat and there isn't any issue with the error we are getting now on ColdSweat-2.1.11.1 hope it helps 👍🏻

**Comment by MikulDev** [comment]
The "latest" version of Cold Sweat seems to be bugged in CurseForge. By manually downloading the latest release by going to the mod's page, it seems to work for me.

**Comment by MisterAndyDandy** [comment]
I just notice that CurseForge or you have updated it again? it is working fine now for me. 

thank you @MikulDev

**Comment by MikulDev** [comment]
You're welcome. I've re-uploaded the file a couple times because people kept finding a bunch small bugs. Anyway, glad this helped ;)
