### ISSUE TITLE
Major Temperature Issue (1.19.2/ColdSweat-2.2-b04i.jar)

### ISSUE THREAD

**Issue by SHXRKIEgg** [Momo-Studios/Cold-Sweat-Rework-Forge#138]
**Describe the bug**
When one player is in the Overworld and the other is in the Nether, the temperature gets buggy and increases and decreases a lot.

**To Reproduce**
1. Create server
2. One person stay in overworld
3.  Second person goes to nether
4. Watch temperature get buggy

**Expected behavior**
Not to be buggy or  increases and decreases a lot.

**Additional context**
Here is a video and another bug report from my Modpack
https://streamable.com/vhy0hr
https://github.com/LunaPixelStudios/SteamPunk/issues/6
[2023-07-15-1.log](https://github.com/Momo-Studios/Cold-Sweat/files/12062981/2023-07-15-1.log)

**Comment by MikulDev** [comment]
Good catch, and thanks for the detailed report. This is in fact an issue on my end, and a pretty critical one at that. The result was that all players would "share" their temperature information with each other, and it would jump back and forth between what each player's temperature should be (because your friend was in the Nether, it would jump up to their temperature, then back down to yours, etc).

Anyway, I managed to get this solved just in time for the next update, so that will be out in a few minutes.
