### ISSUE TITLE
Biome/Dimension compat considerations

### ISSUE THREAD

**Issue by ColonelGerdauf** [Momo-Studios/Cold-Sweat-Rework-Forge#148]
- Biomes O Plenty
- Undergarden
- Blue Skies [cold by default]
- Twilight Forest
- Ad Astra
- Atmospheric
- Neapolitan
- Bumblezone
- missing biomes in vanilla and Biomes You'll Go

**Comment by MikulDev** [comment]
BOP, BYG, Atmospheric, and Vanilla are all supported. Any biomes you don't see in the config are missing because the normal temperature was fine. If you aren't happy with them, you are free to change them.

As for the rest, you are also free to configure those how you like. I may add support for these mods but it isn't a priority right now.

**Comment by ColonelGerdauf** [comment]
When the config file mentions offsets, what is the number based on? Is 0 meaning default (no change)?
