### ISSUE TITLE
Incompatibility with Valkyrien Skies Eureka Mod.

### ISSUE THREAD

**Issue by 301haru** [Momo-Studios/Cold-Sweat-Rework-Forge#162]
https://www.curseforge.com/minecraft/mc-mods/valkyrien-skies
https://www.curseforge.com/minecraft/mc-mods/eureka-ships

There is a problem that temperature does not vary inside ship. (no effect with boiler)
This problem occurs because i guess valkyrien skies mod implement ship by making ship dock area in somewhere like -28866555 12290000 (coordinate) and renders the ship? 
So that temperature actually varies at the ship dock area but not at the actual ship position.

I can explain more with videos if needed.

**Comment by MikulDev** [comment]
It's a bit hard for me to understand the issue here. What does the boiler have to do with any of this?

**Comment by 301haru** [comment]
so at the cold place, normally if you make a house and put boiler and put coal, temperature goes up
But
if you make a house and turn that into ship 
![image](https://github.com/Momo-Studios/Cold-Sweat/assets/39460338/2ac449b3-64cd-4e4c-91e9-72c7b8bfb2e1)
![image](https://github.com/Momo-Studios/Cold-Sweat/assets/39460338/0e875b83-77d8-4502-8f7e-24ad48be01b4)

temperature is same as the environment, does not change, no insulation efect

**Comment by MikulDev** [comment]
This is probably because when you turn it into a ship, the blocks don't "exist" in the traditional sense anymore. They become fake blocks that can be rotated and moved. This also means their functionality is disabled. There's nothing I can do about this. I doubt any other functional blocks work either (chests, furnaces, blocks from other mods, etc.)

It could also be because the hearth needs a roof of solid blocks to work properly, and the ship really isn't solid blocks

**Comment by 301haru** [comment]
yes block doesn't actually exist, it exists at the place where it is called _ship dock area_ at -28866555 12290000 somewhere like here. 
But blocks actually work hearth works furnaces, chests actually works fine.
So I guess if we can track where actual ship is, mod can apply temperature to that place?

**Comment by MikulDev** [comment]
I see what you're saying now. I had to play with the mod a bit to get what you're talking about. Simply put, there really isn't a way this can work. Since the blocks are technically millions of blocks away, they won't warm you up or insulate you; even though they _appear_ to be right next to you. This is the result of how Eureka/Valkyrien Skies works.

**Comment by 301haru** [comment]
Okay then I there's not much thing to do to fix this i guess.. :(

**Comment by MikulDev** [comment]
Sorry, if it wouldn't be so difficult to make compatibility for it, I would. That's a cool mod, but unfortunately not worth the effort right now.
