### ISSUE TITLE
[1.20.1][OPTFINE] Goat & Hoglin Armor Model Error

### ISSUE THREAD

**Issue by linstar-fxt** [Momo-Studios/Cold-Sweat-Rework-Forge#180]
Cold Weat Version: v2.2.1 (newest build)
Forge Version: 47.2.0
Optfine Version: I6 pre6
Log & Error Output: None 

It just looks like this:
![image](https://github.com/Momo-Softworks/Cold-Sweat/assets/75189571/19543285-f642-4ffd-9412-54f381392c6d)

**Comment by MikulDev** [comment]
It looks like Optifine is doing some kind of weird squashing to the armor texture. I tried with a square texture (128x128) and it had a similar effect. I also tried another mod that adds 3D armor models, and the same thing happens. 
Considering Optifine can't even load into a world unless you use the previews, I'd say it's in a pretty rough state at the moment. It's very likely their issue.

I'd honestly suggest you just move to a Sodium port for now (like Rubidium, Embeddium, etc.). These mods are built on a much more modern framework and often don't have these random compatibility issues that Optifine is now infamous for. I will be closing this issue because it seems pretty open-and-shut to me.
