### ISSUE TITLE
Add the ability for the hearth to work on Create contraptions.

### ISSUE THREAD

**Issue by DaddySpin** [Momo-Studios/Cold-Sweat-Rework-Forge#196]
It would be awesome if you could use the hearth on a create contraptions, like just imagine having a cooled train moving through the nether and not overheating.

**Comment by MikulDev** [comment]
This is similar in concept to #162. While it would be very cool, unfortunately in a Create contraption all of the blocks are "fake" blocks. They have a hitbox and render, but that's about it. The hearth in this scenario would be disabled, so it wouldn't be possible for it to warm you up while moving

**Comment by TraipsingShadow** [comment]
I apologize for replying to this already-closed issue, but I wanted to know if Create declares what blocks are part of the contraption (let's say a train)?

As a mod dev, could you hypothetically figure out what blocks are part of the train? Can your mod figure out if one of its blocks were used in a Create contraption?

Adding to that, can you also query for inventories found in the contraption?

And finally, and perhaps most importantly, does Create expose/allow this mod to know if a Player is on a specific contraption (say, how Create knows that a Player is standing inside a train so the Player will be moved along with it)?

To combine everything together:
If this mod can somehow figure out if the Hearth was built part of the contraption, and if this mod can query and grab the items in the inventory of the contraption, and if this mod can figure out if the Player is on that specific train, then it no longer becomes an issue for the most part since the mod can simply provide the Insulation X effect to a player.

So, the mod (hypothetically, I unfortunately do not know coding):
1. Checks if Player is onCreateContraption (true/false), if true then grab the contraptionUUID
2. Checks if the contraption hasHearth (true/false), if true then proceed to 3
3. Checks contraption inventory for Cold Sweat-tagged fuel types, either cold or hot
4. Grab any fuel type (doesn't matter if cold or hot) and its "burn time"
5. Apply Insulation X to Player for as long as there is a fuel that keeps the hearth fed.

I'm just assuming everything here, but if there even is a tiny possibility of this system working, that'd be super neat! Freezing in the middle of a very long train track through a snowy forest isn't exactly a pleasant train ride, hehe.
