### ISSUE TITLE
[1.20.1] Hearth "Show Air Particles" Option Defaults ON

### ISSUE THREAD

**Issue by AetheriMC** [Momo-Studios/Cold-Sweat-Rework-Forge#212]
Minecraft v1.20.1
Forge v47.2.4
Cold-Sweat v2.2.5.1

Hi!

The "Show Air Particles" option for the hearth seems to revert to an "ON" state any time the game is reloaded. This creates a need to manually turn off the hearth's particles upon every reload.

While the toggle option is fantastic, it would be preferable if the option had a default state of "OFF" instead, otherwise the smog in my village gets way out of hand.

Thanks!

**Comment by MikulDev** [comment]
I can confirm this issue is present in 1.20. I've found a fix that works on servers and in singleplayer. It'll be a part of the next update. 

As for making "off" the default option, I don't think I'll do that because the particles are nice and many people seem to enjoy the ambience. I hope it will be less frustrating when the bug is fixed and you can just set-and-forget it.
