### ISSUE TITLE
[1.20.1] Error Parsing Biome Temp Config - Inhospitable Biomes

### ISSUE THREAD

**Issue by MysticcWaters** [Momo-Studios/Cold-Sweat-Rework-Forge#215]
Upon loading up my game, I get the following errors in my log for all biomes:

![image](https://github.com/Momo-Softworks/Cold-Sweat/assets/130418925/86ad3a2b-c592-4478-9682-b8db32430f0b)

This seems to result in all biomes not having the proper temperature settings (and also gives me the Inhospitable advancement on world load). I thought it might be an issue with my other mods, but it occurs even with just Cold Sweat and Biomes O' Plenty.

I'm using Cold Sweat 2.2.5.1 on Forge 47.2.0.

**Comment by MikulDev** [comment]
This occurs normally, even when things aren't wrong. This is because the configs are loaded twice, once when the game first boots, then again when the world is loaded. Because biomes aren't loaded when the game is first started, they appear as "nonexistent" in the eyes of Cold Sweat. This is why the error log says "the biome may not be loaded yet", because in this case it isn't.

In any case, I can't re-create your strange behavior in the same setup. I will say that your forge version is pretty out-of-date, though. It's 20 versions behind. This may be it, I have no idea because I don't have the full log

**Comment by MysticcWaters** [comment]
I can share my latest.log:

[latest.log](https://github.com/Momo-Softworks/Cold-Sweat/files/13999833/latest.log)

As for the Forge version, yeah. I used the version that Prism Launcher defaulted my custom instance to, but after updating to 47.2.20 the same strange behavior seems to occur. It could possibly be a Prism Launcher instance thing, but I wouldn't know what to do about that other than recreating my instance.

**Comment by MysticcWaters** [comment]
Updating this to say that I tried recreating a new instance in Prism Launcher with just Cold Sweat, Biomes O' Plenty, and Terrablender on Forge 47.2.20, and the same issue occurred. All biome temperatures seem to be set incorrectly, and no matter where I spawn it is Inhospitable.

**Comment by MysticcWaters** [comment]
For whatever reason, the biome temperatures seem fine now? I didn't change anything, just re-added the Cold Sweat JAR to my pack. I don't know why, but I think that might have been a separate issue from getting the Inhospitable advancement on world load, since I'm still encountering that.

**Comment by MikulDev** [comment]
Very interesting indeed. I couldn't tell you one way or the other. I'm glad you were able to resolve it regardless.
