### ISSUE TITLE
[Suggestion] Configuration that allows other blocks to work like Hearth

### ISSUE THREAD

**Issue by ghost** [Momo-Studios/Cold-Sweat-Rework-Forge#218]
On many occasions, there will be many blocks which are supposed to work like _Hearth_ in the modpacks, such as the _air conditioner_ in many decorative mods. However, I can't let them enable to make rooms warm like _Hearth_. If there is a way to do that, it will be better.
  Thus, you can add a configuration to allow other blocks to work like _Hearth_, in my opinion.
  The configuraion can be a list like this:
[["block_1", "nbt_1", strength],["block_2", "nbt_2", strength]... etc]

**Comment by MikulDev** [comment]
This would be pretty difficult, if not impossible to implement effectively. When giving hearth functionality to the icebox and boiler, I had to rewrite a lot of code to make them work properly with this added feature. That's a liberty I have with my own blocks, but not other mods' stuff.

 There's also the fact that the hearth is a tile entity, which is basically just a.more advanced version of a block. The issue here is that only one tile entity can exist per block, which means the hearth functionality would be replacing the existing functionality, which would inevitably cause a whole load of other problems when the mod is expecting that functionality to be there. Correct me if I'm wrong about any of this, but I just don't think it's practical.
