### ISSUE TITLE
Custom item names shift the insulation tooltip

### ISSUE THREAD

**Issue by SiverDX** [Momo-Studios/Cold-Sweat-Rework-Forge#236]
![image](https://github.com/Momo-Softworks/Cold-Sweat/assets/22003703/3243b556-4304-4bb8-aff2-3f56af4a0748)

![image](https://github.com/Momo-Softworks/Cold-Sweat/assets/22003703/ce83f6b7-f95d-4c0b-b733-ee1774375556)

See

https://github.com/Momo-Softworks/Cold-Sweat/blob/a67b1e5833f1bd2b7e0252153da9132c43214cad/src/main/java/com/momosoftworks/coldsweat/client/event/TooltipHandler.java#L54-L64

```
empty[style={color=white}, siblings=[translation{key='misc.apotheosis.affix_name.three', args=[translation{key='affix.irons_spellbooks:armor/attribute/mana', args=[]}[style={}], translation{key='item.minecraft.leather_helmet', args=[]}, translation{key='affix.apotheosis:armor/attribute/stalwart.suffix', args=[]}[style={}]]}[style={color=#ED7014}]]]
```

**Comment by SiverDX** [comment]
Might only occur with https://www.curseforge.com/minecraft/mc-mods/apotheosis since anvil renames stores the name in a tag

**Comment by MikulDev** [comment]
I'm not sure why this might be happening. I can't seem to recreate the issue
![image](https://github.com/Momo-Softworks/Cold-Sweat/assets/24680934/9c0e484e-ffb6-436d-ab0e-5de945b0754d)

It could be that other mod that adds all the other information like durability, protection, etc at the top of the tooltip

**Comment by SiverDX** [comment]
It's from Obscure API but if you disable it:

![image](https://github.com/Momo-Softworks/Cold-Sweat/assets/22003703/f725d73e-a9bd-4e9f-87c7-ca8c5999f292)

**Comment by MikulDev** [comment]
Figured it out, this only happens in 1.19. I was testing in 1.20. I believe this is happening because I was using `ItemStack#getDisplayName()` to find the line where the item's name is, when I should have been using `ItemStack#getHoverName()`. 
It seems like the first one just gets the item's name from NBT (which would work for anvil-named items, as you mentioned, but not names set by other means), and the second one actually returns the item's name as it is displayed.

I also figured out that directly comparing Components isn't the way to go, since they don't have a custom equals() method and it just compares the hash, which can be fickle. I decided to compare the string representation of the lines and had better results.
