### ISSUE TITLE
Feature requests: underground temperatures, enclosed areas

### ISSUE THREAD

**Issue by swedneck** [Momo-Studios/Cold-Sweat-Rework-Forge#27]
I don't know how difficult this would be to implement, but it would be nice if temperatures could be made less extreme when going underground, lower when not in sunlight, and higher when in enclosed areas.

This would let players hide from the scorching sun in deserts, use caves as shelter from extreme environments, and houses would be more useful.

Even something very basic like a simple height check plus sky check to see if you're underground, and a sky check to see if you're in direct sunlight, would do a lot to make extreme environments (mostly deserts) be more interesting since you have more ways to manage your temperature.

**Comment by MikulDev** [comment]
I'm not too sure about the enclosed space thing. Sounds pretty exploitable to me.
I've been tossing around the idea of shade affecting the player for a while, so that one's a _maybe_
And as for caves, there's already a system in place that makes temperatures less extreme as you go down, but it's pretty old so I might spruce it up and rebalance it a bit.

**Comment by swedneck** [comment]
Hm, could you give an example of enclosed areas being warmer being exploitable? To me it seems no different than any other method of heating yourself up in terms of balance, so long as it's less effective than anything that costs more resources.

Ah, i presume it just takes *a lot* of depth for it to be noticeable then? Intuitively I'd expect it to kick in like even just a few blocks below the surface.

**Comment by MikulDev** [comment]
We've recently developed some much better ways of detecting depth/blocks above the player, so yeah, the old system of testing depth is a bit finicky and ineffective by comparison.

And in the case of exploiting the enclosed area thing, you could very easily just take dirt blocks and encase yourself in a 1x2x1 box when things get tough in a snow biome. And because it would be so much cheaper than getting lava, fire, waterskins, a hearth, etc, it would make everything else obsolete save for a few extreme circumstances. The only way to balance something so easy to get would be to make it so ineffective that it basically does nothing.

**Comment by swedneck** [comment]
Yeah that's fair, though i was imagining that it wouldn't work exactly like other heat generation methods do, rather it would make heat generation inside the structure more effective (pretending that the player is making body heat).

So just surrounding yourself with dirt would be better than nothing, but only be sufficient in very mild temperatures, whereas if you put a proper heat source inside an enclosed structure, then that heat source would heat more than it would standing out in the open (but also block heat from escaping, so you don't benefit if standing on the other side of the wall).
And if the logic can take into account thickness (maybe as an extension of the depth logic if that's possible?) and material, then i think this mechanic could absolutely be made to be balanced and make temperature management more intuitive.

But yes, unlike the other two things i agree that this wouldn't benefit from a basic simple implementation.

**Comment by MikulDev** [comment]
For the performance and time cost that these features would demand, it just isn't very sensible. Detecting if something is inside an enclosed space in an efficient way is a problem I've been trying to solve for months, since the Hearth uses it to know which areas to insulate. I _have_ made it where temperature-affecting blocks have less effect through walls, so there's that to look forward to, I suppose.
