### ISSUE TITLE
List of new features I suggest  

### ISSUE THREAD

**Issue by FilipKompaniets3** [Momo-Studios/Cold-Sweat-Rework-Forge#285]
I propose to add the following features: The player feels colder in the shade, an umbrella that does not allow one to freeze from the rain, the possibility of getting sunstroke, the player warms up a little when running and during other actions, the change of heat and cold occurs more slowly and smoothly, armor is gradually destroyed when protecting  the player, depending on the ambient temperature, when the player drinks any liquid (and even from mods), he becomes a little colder, the torches slightly heat the player.

**Comment by MikulDev** [comment]
Some of these might be good for an addon mod, but maybe not as part of the base mod that everyone has by default.

- Shade is kind of already a thing if you have a large enough roof above you. Covered areas are pretty easy to make, so this feature would likely be exploited a lot if it was more effective.
- Umbrellas don't really fit into the Vanilla+ theme that the mod aims for, but I do agree that maybe water-proof options should be available as special insulation items or something similar.
- Warming up from running and jumping sounds a bit annoying in my opinion, especially in hot biomes. This is a feature of TaN that I don't particularly like, even if it is a bit more realistic.
- I'm not quite sure what you mean by "the change of heat and cold occurs more slowly and smoothly". There is a setting in the config menu that allows you to make changes in temperature smoother; but if that's not what you're looking for, I'd like to know.
- I will not be adding durability to insulation materials or armor. This complicates the insulation system a lot, because adding durability to Vanilla items isn't very easy and is quite invasive to do, which could cause conflicts with other mods. Furthermore, it would get pretty annoying in later stages. I think the difficulty of obtaining the best insulation items in the first place is good enough for balancing.
- Drinking to become colder is something you could configure relatively easily. It's an option in `item-settings.toml`.
- You can also configure torches to heat the player, but I will not be adding that to the mod by default. Torches are very easy to make, so making them heat you up at all would reduce the difficulty of cold biomes way too much.

Thanks for your suggestions. I'm not trying to be too dismissive of new ideas, but the balance of this mod is very delicate and frivolous additions could make the mod too easy or frustrating for players.

**Comment by FilipKompaniets3** [comment]
Okay, I now understand the shortcomings of some of my proposals
