### ISSUE TITLE
Item stack bug can still happen with inventorio toolbelt slots

### ISSUE THREAD

**Issue by Nicodemus111** [Momo-Studios/Cold-Sweat-Rework-Forge#300]
Tested on 2.3-b03d, 1.20.1, forge.

If you have cooked food in a toolbelt slot and then open a furnace and drop more of the cooked food from its gui then it won't stack with the toolbelt food. The toolbelt food will be updated and fixed when opening the inventory (inventorio one works too). 

Can you explain what the exact cause of the stacking issue is? I've been following it for a while and I want to know.

**Comment by MikulDev** [comment]
In essence, the staking issue is caused by items having mismatching NBT tags. Simple items like food don't have an NBT tag at all, but when they are given one, they are technically considered to be a different item to ones without NBT, so they don't stack. 

I can't seem to replicate this issue on the latest beta. I have steak in my toolbelt (which I assume is one of the 4 vertical slots in the inventory?), and when I open a furnace and drop its output onto the ground, the item gets picked up and stacked with my toolbelt items as it should. 

If you've recently updated from a previous version (between 2.3-b01a and 2.3-b02d), then existing items might have this issue, but items created after updating will be fine.

**Comment by Nicodemus111** [comment]
I did some more testing and figured out it was another mod.
