### ISSUE TITLE
[ColdSweat2.1.3] Newest version compatibility issue with ModernUI mod

### ISSUE THREAD

**Issue by Kzeroko** [Momo-Studios/Cold-Sweat-Rework-Forge#31]
https://pastebin.com/MzpVLm8e
Crashes at the starting phase, looks like a mixin issue.
I have to downgrade the version to 2.1.2 in order to make my modpack run.

**Comment by MikulDev** [comment]
ModernUI seems to be using a mixin for the XP bar that directly conflicts with Cold Sweat. I don't think there's anything I can do about this issue, so I have two choices:
- Revert back to 2.1.2's version of XP bar management, which brings up more issues with more mods but never crashes
- Continue using Mixins, since they're more robust and only conflict with mods in extremely specific circumstances, but it will always crash if a conflict happens

From what I see, It's possible that ModernUI is literally the only mod that is incompatible with the XP bar, since it conflicts so perfectly with Cold Sweat that I couldn't see it happening again (frankly, ModernUI's mixin is pretty invasive, but it's also just a very unlucky situation). I will try my best to clear this up, but I can't promise anything

Just understand that I did this because I've gotten lots of reports of mods not displaying critical UI elements because of 2.1.2's way of handling it, so I went with the less invasive option.
