### ISSUE TITLE
Soul lamp incompatibility. 

### ISSUE THREAD

**Issue by SaleDDka** [Momo-Studios/Cold-Sweat-Rework-Forge#315]
![image](https://github.com/Momo-Softworks/Cold-Sweat/assets/57826271/6b5fa706-870e-48e4-bb86-7e96edbd8bf5)

While using soul lamp and any other item with custom hands position, character manages to pull out his third hand. Despite that, player hides the lamp while using vanilla items, like bow or crossbow. I suggest to add a list of items to disable the lantern's render while using them.

**Comment by MikulDev** [comment]
What mod are you using that causes that effect? I'd like to do some testing

**Comment by SaleDDka** [comment]
> What mod are you using that causes that effect? I'd like to do some testing

Just enough guns.

**Comment by MikulDev** [comment]
I got it to somewhat work, though I see an issue in the way that MrCrayfish's Gun Mod (and by extension Just Enough Guns, which is a fork) handles the offhand item. It only moves your offhand down by a certain amount when you equip a gun. This works fine for most items, but the soulspring lamp doesn't get moved down enough to be hidden from view.

The mod developer should consider setting the item's "equip progress" rather than just moving it on-screen. This would make it more compatible with non-standard items, since any item that's big enough would have this issue, not just the soulspring lamp.
