### ISSUE TITLE
Equipping Elytra Softlocks Player

### ISSUE THREAD

**Issue by quek04** [Momo-Studios/Cold-Sweat-Rework-Forge#342]
Wearing an Elytra crashes the client/kicks player and prevents them from rejoining a server on 2.3.1
[crash-2024-08-20_20.49.40-server.txt](https://github.com/user-attachments/files/16684402/crash-2024-08-20_20.49.40-server.txt)

**Comment by MikulDev** [comment]
Thanks for the report. I can confirm that this happens in 1.21. I unfortunately don't have a solution for you in the meantime, but this will be fixed in the next patch, and you will be able to join the server then. 
My advice for now would be to use something like [Dovetail](https://offroaders123.github.io/Dovetail/) or [NBTExplorer](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-tools/1262665-nbtexplorer-nbt-editor-for-windows-and-mac) to edit your player data and remove the elytra item. Otherwise, you can simply delete the player data and the issue will go away.
