### ISSUE TITLE
在尝试给锅炉充能来给玩家温暖效果时发生了错误

### ISSUE THREAD

**Issue by Minecraft0122** [Momo-Studios/Cold-Sweat-Rework-Forge#357]
WIKI中提到：
“当装备烟囱时，锅炉能够为附近的玩家提供温暖效果，最高可达 V （5）级。”
“其样式与壁炉类似。它可以从除顶部或正面以外的任何一侧使用红石充能来激活这一行为。”

但是我给锅炉装备上烟囱，并从底部使用红石块给锅炉充能后，我的服务器报错并崩溃
我尝试重启服务器并进入，但是出现了更多问题
第一次尝试进入时，显示“无效的玩家数据”
第二次尝试时，服务器崩溃，报错内容和第一次崩溃的内容相似
重启服务器并第三次尝试进入服务器时，服务器显示加载超时（单个 tick 耗时 60 秒）并崩溃

在重启服务器的同时，我尝试到单人存档里去测试，但是当我打开冷汗的菜单把温度调整成摄氏度后，我的客户端崩溃了
检查错误报告后，发现错误原因是“无法保存 DynamicHolder 类型的 HashMap”

下面是我客户端的错误报告和服务器的错误报告
[客户端错误报告.zip](https://github.com/user-attachments/files/16790640/default.zip)
[服务端错误报告.zip](https://github.com/user-attachments/files/16790641/default.zip)

**Comment by MikulDev** [comment]
The server error is because you are using an outdated version of Cold Sweat (2.3.1). The most recent version is 2.3.3, and it has been fixed.

As for the client error, I noticed this in the error log: "另一个程序正在使用此文件，进程无法访问。" 
("Another program is using this file and the process cannot access it.")
Somehow windows believes there is another program accessing the configuration file, preventing it from being accessed. 

There might, or might not, be another program using it; Windows tends to give this error sometimes even if that's not the case.

**Comment by Minecraft0122** [comment]
> 服务器错误是因为您使用的是过时的 Cold Sweat （2.3.1） 版本。最新版本是 2.3.3，已修复。
> 
> 至于客户端错误，我在错误日志中注意到了这一点：“另一个程序正在使用此文件，进程无法访问。“ （”另一个程序正在使用此文件，进程无法访问它。”）不知何故，Windows 认为有另一个程序正在访问配置文件，从而阻止它被访问。
> 
> 可能有，也可能没有，其他程序使用它;Windows 有时往往会给出此错误，即使情况并非如此。

感谢您回复。我希望将冷汗WIKI上的内容转载到中国的MC百科（www.mcmod.cn），以便让更多中国玩家知道模组的用法和玩法。为了遵循版权规定和MC百科的编辑政策，我需要获得冷汗的正式许可。由于中国对访问外网的限制，我无法合法的连接到discord，同时在中国访问GitHub也非常不稳定，经常遇到连接问题。因此，能否使用别的方法询问是否可以允许我转载WIKI上的内容
