### ISSUE TITLE
Heatstroke effect incompatible with reBlured

### ISSUE THREAD

**Issue by Kielbashnikov** [Momo-Studios/Cold-Sweat-Rework-Forge#361]
I had problem with blur effect not fading away after cooling. It only dissapeared after restart of the game. I figured out visual connection with opening HUDs while having reBlured mod installed. After removing reBlured, problem has been solved.

**Comment by MikulDev** [comment]
This might be an issue with ReBlurred. My guess is that when they apply their blur effect to the background, they don't re-apply the old effect properly when the menu closes. Shaders are tricky in Minecraft because you can only have one active at a time, so it makes juggling effects added by multiple mods very difficult.

**Comment by Kielbashnikov** [comment]
Fair, I should go and place a querry on their site as well then.
Thank you for response.

**Comment by MikulDev** [comment]
I will be closing this issue, since I forgot this has actually been an issue for [quite a while now](https://github.com/Cheaterpaul/ReBlured/issues/5). I will reopen the original issue if it is confirmed that Cold Sweat is at fault for this incompatibility.
