### ISSUE TITLE
No Longer Possible to Turn of Ice Block Temperature Effect

### ISSUE THREAD

**Issue by torchdeveloper** [Momo-Studios/Cold-Sweat-Rework-Forge#365]
In previous versions ice only froze you because it was listed in the config with a blocktemp, but now despite not being present in the blocktemp list it still decreases the player's temperature, and as far as I can tell there is no longer a way to disable this.

**Comment by MikulDev** [comment]
If you add it to the Block Temperatures section with a temperature of 0, it will effectively disable it.

**Comment by torchdeveloper** [comment]
I tried that, but it didn't work.

**Comment by torchdeveloper** [comment]
thank you for such a quick response tho!

**Comment by MikulDev** [comment]
Ok, I've done some testing and you are correct. Because of the way config settings *stack* rather than *replace* each other, adding a config with ice's temperature set to 0 doesn't do anything. I was able to rework the system so that the ice block temperatures are now back to being defined in TOML, so they can be edited.

 I also made some changes to how to load order works, so for cases in the future in which you need to change a block temperature that isn't defined in TOML, you can make a JSON config under `config/coldsweat/data` that overrides it.
