### ISSUE TITLE
Armor insulation bug

### ISSUE THREAD

**Issue by Mrpurple007** [Momo-Studios/Cold-Sweat-Rework-Forge#370]
Armor insulation doesn't show normally
Goat fur, hoglin hide, chameleon molt, etc. add more insulation points

**Comment by MikulDev** [comment]
What do you mean by this? Can you elaborate?

**Comment by Mrpurple007** [comment]
> What do you mean by this? Can you elaborate?

Yes, about first, the armor insulation scale is showing shorter like x24
about second, the chameleon molt adds 4 ins. points instead of 2 for example (i can drop screenshot but they are not adding)

**Comment by Mrpurple007** [comment]
and also when trying to add armor pieces like goat fur paka to chestplate that don't works

**Comment by Mrpurple007** [comment]
![Uploading issue post 2.jpg…]()

**Comment by MikulDev** [comment]
The armor insulation tooltip (the "x24" part) is normal. Any insulation that exceeds 10 bars will be shown differently to make it more compact and easier to read. The amount of insulation provided by items is getting out of hand due to an error in how configs are loaded, resulting in the amount of insulation provided by items doubling every time the world is re-joined. We are discussing solutions for this on the Discord server.
