### ISSUE TITLE
crash during game loading

### ISSUE THREAD

**Issue by pibblepower** [Momo-Studios/Cold-Sweat-Rework-Forge#383]
I tried adding the mod to a modified ATM 9 pack, but the mod causes the game to crash when loading the game. I'm playing on forge 1.20.1. Here's the crash report: 
[crash-2024-10-05_22.21.17-client.txt](https://github.com/user-attachments/files/17267912/crash-2024-10-05_22.21.17-client.txt)

**Comment by MikulDev** [comment]
I don't see any mention of Cold Sweat as a possible source of the issue. Are you sure it's the mod that causes the crash?

**Comment by P4YN-Ki** [comment]
This isn't because of Cold Sweat at all, it's because you're conflicting your Renderer's, it even tells you at the top of your log.

Disable one of the rendering-related mods (like entity_model_features, dynamiclightsreforged, or oculus) and test if the game starts without crashing.

Embeddium doesn't like you having those enabled with it.

// Embeddium instance tainted by mods: [dynamiclightsreforged, entity_texture_features, oculus]
