### ISSUE TITLE
The method getTemperatureAt() in Temperature.java will cause memory leak

### ISSUE THREAD

**Issue by moguang2004** [Momo-Studios/Cold-Sweat-Rework-Forge#394]
I call this method in my mod to get the world temperature one time per tick and find the memory use will continuously increase. I guess is the dummy player that occupied the memory and didn't be released properly.
![image](https://github.com/user-attachments/assets/d57f92da-55c5-4ae0-9c6c-10d73076e8e2)

**Comment by MikulDev** [comment]
I see. I'm not sure why that would be the case, because there should only be one per dimension ID. How do you know that this particular method is the one that causes the memory leak?

Some advice, as well, is that you likely don't need to run this every tick. Because getting the world temperature is a pretty complex operation, it would help performance if you made this check every 5, 10, or even 20 ticks
