### ISSUE TITLE
Fabric Seasons support

### ISSUE THREAD

**Issue by vico93** [Momo-Studios/Cold-Sweat-Rework-Forge#410]
Could you add compatibility with [Fabric Seasons](https://modrinth.com/mod/fabric-seasons) by @lucaargolo ?

It's a great lighweight alternative to Serene Seasons on Fabric.

**Comment by MikulDev** [comment]
I'm assuming you're using Sinytra Connector, since Cold Sweat is a (Neo)Forge mod. And since mixins don't function properly with Sinytra in anything other than NeoForge, this compat would be limited to 1.21.

With that said, though, it seems like there's already some level of natural compatibility, as the world temperature does change with the seasons. What other compatibility would be needed?

**Comment by vico93** [comment]
Uh sorry, i didnt paid attention that this mod is (unfortunately) (Neo)Forge-only.

Please ignore this then.
