### ISSUE TITLE
Why are portals extremely hot?

### ISSUE THREAD

**Issue by ALEILGOD** [Momo-Studios/Cold-Sweat-Rework-Forge#412]
I was testing cold sweat with a custom modpack, and i entered the twilight forest, at the spawn there were 425 degrees, and when i exited the dimension, the spawn area was the same temperature (also i spawned 50 blocks in the air), idk if this is normal or not.
Something similar happens when i enter the everbright and the portal in the overworld is cold, like 42 degrees.
The everdawn is like 140 degrees hot
I haven't tested this in other portals but theese three are like this

**Comment by MikulDev** [comment]
There may be some kind of configuration issue or conflict in your modpack, because Twilight Forest portals don't emit temperature, and neither do the ones from Blue Skies. The fact that the Twilight Portal is acting strangely could also indicate that there's some kind of issue with the modpack itself. I tested these things myself and didn't have any of the issues you're describing.
