### ISSUE TITLE
Daily Temperautre Fluctuations

### ISSUE THREAD

**Issue by MikulDev** [Momo-Studios/Cold-Sweat-Rework-Forge#56]
Hello，Dear author，Please forgive me，In fact, my English is not well, just some simple communication.May I induige in a IittIe advice?
This is a good mod，I hope it can add the temperature change in the time interval to "config"。
For instance,When entering the game time: 0-24000 a day,temperature，Use default settings;time:24000-48000，
Temperature rise 0.2;time:48000-72000,Temperature drop 0.2。Keep repeating，It's the same all year round。
I wonder if you can understand，Sorry, my English is not very good. 
I hope you can take my advice。

_Originally posted by @XLB9363 in https://github.com/Momo-Studios/Cold-Sweat/issues/52#issuecomment-1123891567_

**Comment by XLB9363** [comment]
I 'm sorry，I used GitHub for the first time。I hope the temperature can change periodically with time.

**Comment by XLB9363** [comment]
I 'm sorry，I used GitHub for the first time。I hope the temperature can change periodically with time.

**Comment by MikulDev** [comment]
I don't really understand the reasoning behind this. Why would temperature change in this pattern from day to day? I would understand random changes in temperature depending on the day, because that's something that happens in real life, but this just doesn't make a lot of sense. I'll consider doing the random changes, though, since that makes sense from a realistic perspective.

**Comment by XLB9363** [comment]
I try to make it as clear as possible，My world is 24000 a day,For example, 1 to 30 days is spring，31 to 60 days are summer
61 to 90 days is autumn，91 to 120 days are winter。It can keep the temperature unchanged for 1-30 days，The temperature of all formations increased by 0.2 in 31-60 days，The temperature changes back to the initial temperature from 61 days to 90 days，From 91 days to 120 days, the temperature decreased all formations by 0.2。
My idea is to match coldsweet with simple seasons, so that there will be temperature changes throughout the year.

**Comment by MikulDev** [comment]
Oh, so you just want us to add seasons. Cold Sweat already has built-in compatibility with **Serene Seasons** and **Better Weather** (discontinued). We do not have plans to add seasons ourselves any time soon.
