### ISSUE TITLE
Suggestion: Crop growth uses temperature 

### ISSUE THREAD

**Issue by ExpensiveKoala** [Momo-Studios/Cold-Sweat-Rework-Forge#77]
Much like how Serene Seasons affect crop growth, this mod could also make the local temperature affect crop growth.

Winter crops can grow in Summer if the area around it is cold enough, etc...

**Comment by MikulDev** [comment]
We've been tossing around the idea of separate add-on mod that does something like this. It'll be pretty far out unless a developer would be willing to make a compat mod. I agree that the idea is fitting with Cold Sweat's general vibe, though.

**Comment by ExpensiveKoala** [comment]
I wouldn't mind making that addon mod. Was considering making a thirst addon anyways.
Don't know how much would need to change in the API to enable such features though.

**Comment by MikulDev** [comment]
I don't know either. It's not really designed for non-entities to be affected by temperature but it might be possible with some trickery.

**Comment by MikulDev** [comment]
I don't know if you're still interested in this feature, but there have been a lot of changes under the hood that would make this feasible to implement, such as methods that get the ambient temperature at a certain location. 

Development is slowing down so I intend for features to not change much going forward, so any mod developed should be fairly future-proof. Either way, I'll be closing this issue, because I don't think this feature is in the cards for being integrated into the base mod. It's still a good idea, though!
