### ISSUE TITLE
Diving temperature drop advice.

### ISSUE THREAD

**Issue by Accidey** [Momo-Studios/Cold-Sweat-Rework-Forge#90]
I found a problem, when I'm in a hot environment, my body temperature still doesn't drop when I'm in the water, this is very unscientific, maybe you should add a setting that the body temperature will drop slowly when diving. In addition to this, when the Y value is getting lower and lower, the body temperature should drop even in hot communities. I hope you can take both of these suggestions. Your mod is really fun.v( •̀ ω •́ )✧

**Comment by MikulDev** [comment]
Water affects the ambient (world) temperature, and I intend to keep it that way. Water doesn't "scientifically" affect your body's temperature directly anyway, it just transfers heat away from your skin at a faster rate because it's denser. 

I tried to implement a system like this, but it just doesn't make sense. In a hot environment, the player's temperature will continue to go up, fighting the effects of the water and making it ultimately useless.

A good idea of yours, though, is making water more effective at greater depths. I'll consider implementing that somehow.
